/*
 * H_Bridge_config.h
 *
 *  Created on: Nov 11, 2021
 *      Author: hamdy
 */

#ifndef H_BRIDGE_H_BRIDGE_CONFIG_H_
#define H_BRIDGE_H_BRIDGE_CONFIG_H_

#define MOTOR1_STATE		CONNECTED		// CONNECTED or NOT_CONNECTED
#define MOTOR2_STATE		NOT_CONNECTED

/*		MOTOR 1 CONFIGURATION	*/
#define MOTOR1_EN_PORT		DIO_u8PORTD
#define MOTOR1_EN_PIN		DIO_u8PIN4

#define MOTOR1_DIR			CW				// CW or CCW

#define MOTOR1_INPUT_PORT	DIO_u8PORTC
#define MOTOR1_INPUT_PIN	DIO_u8PIN3

#define MOTOR1_OUTPUT_PORT	DIO_u8PORTC
#define MOTOR1_OUTPUT_PIN	DIO_u8PIN4

/*		MOTOR 2 CONFIGURATION	*/
#define MOTOR2_EN_PORT		DIO_u8PORTD
#define MOTOR2_EN_PIN		DIO_u8PIN5

#define MOTOR2_DIR			CCW				// CW or CCW

#define MOTOR2_INPUT_PORT	DIO_u8PORTC
#define MOTOR2_INPUT_PIN	DIO_u8PIN5

#define MOTOR2_OUTPUT_PORT	DIO_u8PORTC
#define MOTOR2_OUTPUT_PIN	DIO_u8PIN6



#endif /* H_BRIDGE_H_BRIDGE_CONFIG_H_ */
